version: "3.7"
services:
    blog_service:
        image: dillonnys/grpc-mongo:latest
        build:
            context: .
        ports: 
            - "50051:50051"
            - "8081:8081"
    blog_db:
        image: mongo:4.2
        volumes:
            - ~/mongo/data/db:/data/db
        expose:
            - "27017"