version: "3.7"
services:
    greet_service:
        image: dillonnys/grpc-mongo:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "50051:50051"