// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog.proto

// Service for creating, reading, updating, and deleting Blog items.

package blogpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// A request with the blog to create in the database
type CreateBlogRequest struct {
	// The blog item to create in the database
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRequest) Reset()         { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()    {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}

func (m *CreateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequest.Unmarshal(m, b)
}
func (m *CreateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequest.Marshal(b, m, deterministic)
}
func (m *CreateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequest.Merge(m, src)
}
func (m *CreateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequest.Size(m)
}
func (m *CreateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequest proto.InternalMessageInfo

func (m *CreateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

// A response with the newly-created blog
type CreateBlogResponse struct {
	// The newly created blog with a set ID field
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogResponse) Reset()         { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()    {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}

func (m *CreateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogResponse.Unmarshal(m, b)
}
func (m *CreateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogResponse.Marshal(b, m, deterministic)
}
func (m *CreateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogResponse.Merge(m, src)
}
func (m *CreateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBlogResponse.Size(m)
}
func (m *CreateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogResponse proto.InternalMessageInfo

func (m *CreateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogRequest)(nil), "blog.CreateBlogRequest")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
}

func init() {
	proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1)
}

var fileDescriptor_6745b25902462fb1 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xe9, 0xba, 0xfe, 0xe9, 0x14, 0x04, 0x07, 0xc1, 0xa0, 0x20, 0xd2, 0x93, 0x17, 0x37,
	0xb4, 0xf5, 0x2e, 0xd4, 0x93, 0x17, 0x0f, 0xf5, 0xe6, 0x45, 0xba, 0x9b, 0x21, 0x0d, 0xec, 0x66,
	0xd6, 0x64, 0xb6, 0xe0, 0xb7, 0x97, 0x4d, 0x10, 0x85, 0x1e, 0xbc, 0xe5, 0xbd, 0x99, 0x79, 0xef,
	0x47, 0x00, 0xea, 0x96, 0x6d, 0xd5, 0x07, 0x16, 0xc6, 0x72, 0x7c, 0xcf, 0x1b, 0x28, 0xd7, 0x2d,
	0x5b, 0x3c, 0x87, 0xc2, 0x19, 0x35, 0xb9, 0x9b, 0xdc, 0x4f, 0x37, 0x85, 0x33, 0x78, 0x03, 0xd3,
	0xed, 0x20, 0x3b, 0x0e, 0x1f, 0xce, 0xa8, 0x22, 0xd9, 0x67, 0xd9, 0x78, 0x31, 0x78, 0x09, 0xc7,
	0xe2, 0xa4, 0x25, 0x75, 0x94, 0x06, 0x59, 0xa0, 0x82, 0xd3, 0x86, 0xbd, 0x90, 0x17, 0x55, 0x26,
	0xff, 0x47, 0xce, 0x57, 0x70, 0xf1, 0x1c, 0x68, 0x2b, 0x34, 0x56, 0x6d, 0xe8, 0x73, 0xa0, 0x28,
	0x78, 0x0b, 0x89, 0x20, 0x75, 0xce, 0x96, 0x50, 0x25, 0xb4, 0xb4, 0x90, 0xc9, 0x1e, 0x01, 0xff,
	0x1e, 0xc5, 0x9e, 0x7d, 0xa4, 0xff, 0xae, 0x96, 0xaf, 0x30, 0x1b, 0xd5, 0x1b, 0x85, 0xbd, 0x6b,
	0x08, 0x9f, 0x00, 0x7e, 0x43, 0xf0, 0x2a, 0xaf, 0x1f, 0xb0, 0x5c, 0xab, 0xc3, 0x41, 0xee, 0x5b,
	0x2f, 0xde, 0xb5, 0x75, 0xb2, 0x1b, 0xea, 0xaa, 0xe1, 0x4e, 0x1b, 0xff, 0x15, 0x17, 0xda, 0x86,
	0xbe, 0x79, 0xe8, 0xd8, 0x5b, 0xd6, 0x91, 0xc2, 0x9e, 0x82, 0xee, 0xd8, 0x50, 0xab, 0xc7, 0x8c,
	0xbe, 0xae, 0x4f, 0xd2, 0xff, 0xae, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x43, 0xe8, 0xb6, 0x11,
	0x6d, 0x01, 0x00, 0x00,
}
