// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog.proto

// Service for creating, reading, updating, and deleting Blog items.

package blogpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The status of reading the blog from the database.
type ReadBlogResponse_ReadStatus int32

const (
	ReadBlogResponse_UNKNOWN   ReadBlogResponse_ReadStatus = 0
	ReadBlogResponse_NOT_FOUND ReadBlogResponse_ReadStatus = 1
	ReadBlogResponse_FOUND     ReadBlogResponse_ReadStatus = 2
)

var ReadBlogResponse_ReadStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_FOUND",
	2: "FOUND",
}

var ReadBlogResponse_ReadStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"NOT_FOUND": 1,
	"FOUND":     2,
}

func (x ReadBlogResponse_ReadStatus) String() string {
	return proto.EnumName(ReadBlogResponse_ReadStatus_name, int32(x))
}

func (ReadBlogResponse_ReadStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{4, 0}
}

type UpdateBlogResponse_UpdateStatus int32

const (
	UpdateBlogResponse_UNKNOWN     UpdateBlogResponse_UpdateStatus = 0
	UpdateBlogResponse_NOT_UPDATED UpdateBlogResponse_UpdateStatus = 1
	UpdateBlogResponse_UPDATED     UpdateBlogResponse_UpdateStatus = 2
)

var UpdateBlogResponse_UpdateStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_UPDATED",
	2: "UPDATED",
}

var UpdateBlogResponse_UpdateStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"NOT_UPDATED": 1,
	"UPDATED":     2,
}

func (x UpdateBlogResponse_UpdateStatus) String() string {
	return proto.EnumName(UpdateBlogResponse_UpdateStatus_name, int32(x))
}

func (UpdateBlogResponse_UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{6, 0}
}

type DeleteBlogResponse_DeleteStatus int32

const (
	DeleteBlogResponse_UNKNOWN     DeleteBlogResponse_DeleteStatus = 0
	DeleteBlogResponse_NOT_DELETED DeleteBlogResponse_DeleteStatus = 1
	DeleteBlogResponse_DELETED     DeleteBlogResponse_DeleteStatus = 2
)

var DeleteBlogResponse_DeleteStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_DELETED",
	2: "DELETED",
}

var DeleteBlogResponse_DeleteStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"NOT_DELETED": 1,
	"DELETED":     2,
}

func (x DeleteBlogResponse_DeleteStatus) String() string {
	return proto.EnumName(DeleteBlogResponse_DeleteStatus_name, int32(x))
}

func (DeleteBlogResponse_DeleteStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{8, 0}
}

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// A request with the blog to create in the database
type CreateBlogRequest struct {
	// The blog item to create in the database
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRequest) Reset()         { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()    {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}

func (m *CreateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequest.Unmarshal(m, b)
}
func (m *CreateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequest.Marshal(b, m, deterministic)
}
func (m *CreateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequest.Merge(m, src)
}
func (m *CreateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequest.Size(m)
}
func (m *CreateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequest proto.InternalMessageInfo

func (m *CreateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

// A response with the newly-created blog
type CreateBlogResponse struct {
	// The newly created blog with a set ID field
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogResponse) Reset()         { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()    {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}

func (m *CreateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogResponse.Unmarshal(m, b)
}
func (m *CreateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogResponse.Marshal(b, m, deterministic)
}
func (m *CreateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogResponse.Merge(m, src)
}
func (m *CreateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBlogResponse.Size(m)
}
func (m *CreateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogResponse proto.InternalMessageInfo

func (m *CreateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

// A request with the blog id to read from the database
type ReadBlogRequest struct {
	// The blog's database identifier
	BlogId               string   `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogRequest) Reset()         { *m = ReadBlogRequest{} }
func (m *ReadBlogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBlogRequest) ProtoMessage()    {}
func (*ReadBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{3}
}

func (m *ReadBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogRequest.Unmarshal(m, b)
}
func (m *ReadBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogRequest.Marshal(b, m, deterministic)
}
func (m *ReadBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogRequest.Merge(m, src)
}
func (m *ReadBlogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBlogRequest.Size(m)
}
func (m *ReadBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogRequest proto.InternalMessageInfo

func (m *ReadBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

// A response with the blog item and a status code.
type ReadBlogResponse struct {
	// The blog, if successfully found in the database.
	// This will be null if not found.
	Blog *Blog `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	// The status of reading the blog from the database.
	// This will be NOT_FOUND when the blog couldn't be
	// retrieved or FOUND when it could. Defaults to UNKNOWN
	// in cases of internal errors or unimplemented code.
	Status               ReadBlogResponse_ReadStatus `protobuf:"varint,2,opt,name=status,proto3,enum=blog.ReadBlogResponse_ReadStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ReadBlogResponse) Reset()         { *m = ReadBlogResponse{} }
func (m *ReadBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlogResponse) ProtoMessage()    {}
func (*ReadBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{4}
}

func (m *ReadBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogResponse.Unmarshal(m, b)
}
func (m *ReadBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogResponse.Marshal(b, m, deterministic)
}
func (m *ReadBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogResponse.Merge(m, src)
}
func (m *ReadBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlogResponse.Size(m)
}
func (m *ReadBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogResponse proto.InternalMessageInfo

func (m *ReadBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func (m *ReadBlogResponse) GetStatus() ReadBlogResponse_ReadStatus {
	if m != nil {
		return m.Status
	}
	return ReadBlogResponse_UNKNOWN
}

// A request with the blog info to update
type UpdateBlogRequest struct {
	// The new blog data to replace the old data.
	// It is important to specify the ID so that
	// the old blog can be located.
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBlogRequest) Reset()         { *m = UpdateBlogRequest{} }
func (m *UpdateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogRequest) ProtoMessage()    {}
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{5}
}

func (m *UpdateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogRequest.Unmarshal(m, b)
}
func (m *UpdateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogRequest.Merge(m, src)
}
func (m *UpdateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogRequest.Size(m)
}
func (m *UpdateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogRequest proto.InternalMessageInfo

func (m *UpdateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

// A response after an update request is called.
type UpdateBlogResponse struct {
	// The status of the update operation.
	Status               UpdateBlogResponse_UpdateStatus `protobuf:"varint,1,opt,name=status,proto3,enum=blog.UpdateBlogResponse_UpdateStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateBlogResponse) Reset()         { *m = UpdateBlogResponse{} }
func (m *UpdateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogResponse) ProtoMessage()    {}
func (*UpdateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{6}
}

func (m *UpdateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogResponse.Unmarshal(m, b)
}
func (m *UpdateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogResponse.Merge(m, src)
}
func (m *UpdateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogResponse.Size(m)
}
func (m *UpdateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogResponse proto.InternalMessageInfo

func (m *UpdateBlogResponse) GetStatus() UpdateBlogResponse_UpdateStatus {
	if m != nil {
		return m.Status
	}
	return UpdateBlogResponse_UNKNOWN
}

// A request to delete a blog from the database
type DeleteBlogRequest struct {
	// The id of the blog to delete.
	BlogId               string   `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlogRequest) Reset()         { *m = DeleteBlogRequest{} }
func (m *DeleteBlogRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogRequest) ProtoMessage()    {}
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{7}
}

func (m *DeleteBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogRequest.Unmarshal(m, b)
}
func (m *DeleteBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogRequest.Merge(m, src)
}
func (m *DeleteBlogRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogRequest.Size(m)
}
func (m *DeleteBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogRequest proto.InternalMessageInfo

func (m *DeleteBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

// A response to a DeleteBlog call, with the status of the call.
type DeleteBlogResponse struct {
	// The status of the delete operation.
	Status               DeleteBlogResponse_DeleteStatus `protobuf:"varint,1,opt,name=status,proto3,enum=blog.DeleteBlogResponse_DeleteStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *DeleteBlogResponse) Reset()         { *m = DeleteBlogResponse{} }
func (m *DeleteBlogResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogResponse) ProtoMessage()    {}
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{8}
}

func (m *DeleteBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogResponse.Unmarshal(m, b)
}
func (m *DeleteBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogResponse.Merge(m, src)
}
func (m *DeleteBlogResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogResponse.Size(m)
}
func (m *DeleteBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogResponse proto.InternalMessageInfo

func (m *DeleteBlogResponse) GetStatus() DeleteBlogResponse_DeleteStatus {
	if m != nil {
		return m.Status
	}
	return DeleteBlogResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("blog.ReadBlogResponse_ReadStatus", ReadBlogResponse_ReadStatus_name, ReadBlogResponse_ReadStatus_value)
	proto.RegisterEnum("blog.UpdateBlogResponse_UpdateStatus", UpdateBlogResponse_UpdateStatus_name, UpdateBlogResponse_UpdateStatus_value)
	proto.RegisterEnum("blog.DeleteBlogResponse_DeleteStatus", DeleteBlogResponse_DeleteStatus_name, DeleteBlogResponse_DeleteStatus_value)
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogRequest)(nil), "blog.CreateBlogRequest")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
	proto.RegisterType((*ReadBlogRequest)(nil), "blog.ReadBlogRequest")
	proto.RegisterType((*ReadBlogResponse)(nil), "blog.ReadBlogResponse")
	proto.RegisterType((*UpdateBlogRequest)(nil), "blog.UpdateBlogRequest")
	proto.RegisterType((*UpdateBlogResponse)(nil), "blog.UpdateBlogResponse")
	proto.RegisterType((*DeleteBlogRequest)(nil), "blog.DeleteBlogRequest")
	proto.RegisterType((*DeleteBlogResponse)(nil), "blog.DeleteBlogResponse")
}

func init() {
	proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1)
}

var fileDescriptor_6745b25902462fb1 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x35, 0x71, 0xbb, 0xdb, 0xdc, 0x68, 0xbb, 0x1d, 0xd4, 0x06, 0x05, 0xd1, 0x80, 0x20, 0xa2,
	0x1b, 0xba, 0xeb, 0xcb, 0x3e, 0x48, 0xb1, 0x66, 0x85, 0xa2, 0x64, 0x25, 0x6d, 0x10, 0x7c, 0x59,
	0x92, 0xcc, 0x90, 0x06, 0xb2, 0x99, 0x98, 0x4c, 0x0a, 0xfe, 0x06, 0xc1, 0x1f, 0xe1, 0x2f, 0x95,
	0x99, 0x49, 0x36, 0xe9, 0xce, 0xfa, 0xf5, 0x96, 0x7b, 0xee, 0xc7, 0x39, 0xf7, 0xce, 0x21, 0x00,
	0x51, 0x46, 0x93, 0x49, 0x51, 0x52, 0x46, 0xd1, 0x80, 0x7f, 0xdb, 0x31, 0x0c, 0xce, 0x32, 0x9a,
	0xa0, 0x03, 0xd0, 0x53, 0x6c, 0x69, 0x4f, 0xb4, 0xe7, 0x86, 0xaf, 0xa7, 0x18, 0x3d, 0x02, 0x23,
	0xac, 0xd9, 0x15, 0x2d, 0x57, 0x29, 0xb6, 0x74, 0x01, 0xef, 0x4b, 0xe0, 0x1c, 0xa3, 0x7b, 0xb0,
	0xc7, 0x52, 0x96, 0x11, 0xeb, 0xb6, 0x48, 0xc8, 0x00, 0x59, 0x30, 0x8a, 0x69, 0xce, 0x48, 0xce,
	0xac, 0x81, 0xc0, 0xdb, 0xd0, 0x9e, 0xc1, 0xd1, 0xbb, 0x92, 0x84, 0x8c, 0x70, 0x2a, 0x9f, 0x7c,
	0xad, 0x49, 0xc5, 0xd0, 0x63, 0x10, 0x0a, 0x04, 0xa7, 0x39, 0x85, 0x89, 0x90, 0x26, 0x0a, 0xa4,
	0xb2, 0xd7, 0x80, 0xfa, 0x4d, 0x55, 0x41, 0xf3, 0x8a, 0xfc, 0xb5, 0xeb, 0x05, 0x1c, 0xfa, 0x24,
	0xc4, 0x7d, 0xa2, 0x63, 0x18, 0xf1, 0xd4, 0x6a, 0xb3, 0xdf, 0x90, 0x87, 0xe7, 0xd8, 0xfe, 0xa9,
	0xc1, 0xb8, 0x2b, 0xfe, 0x37, 0x02, 0x34, 0x87, 0x61, 0xc5, 0x42, 0x56, 0x57, 0xe2, 0x2a, 0x07,
	0xd3, 0xa7, 0xb2, 0x62, 0x7b, 0x8e, 0x00, 0x2e, 0x44, 0xa1, 0xdf, 0x34, 0xd8, 0x33, 0x80, 0x0e,
	0x45, 0x26, 0x8c, 0x02, 0xef, 0x83, 0xb7, 0xfc, 0xec, 0x8d, 0x6f, 0xa1, 0xbb, 0x60, 0x78, 0xcb,
	0xcb, 0xd5, 0xfb, 0x65, 0xe0, 0xb9, 0x63, 0x0d, 0x19, 0xb0, 0x27, 0x3f, 0x75, 0x7e, 0xbb, 0xa0,
	0xc0, 0xff, 0x79, 0xbb, 0x1f, 0x1a, 0xa0, 0x7e, 0x57, 0xb3, 0xdb, 0x9b, 0x8d, 0x76, 0x4d, 0x68,
	0x7f, 0x26, 0x1b, 0xd5, 0xca, 0x06, 0xda, 0xd2, 0x3f, 0x87, 0x3b, 0x7d, 0xfc, 0xe6, 0x06, 0x87,
	0x60, 0xf2, 0x0d, 0x82, 0x4f, 0xee, 0xdb, 0xcb, 0x05, 0xdf, 0x81, 0x67, 0x9b, 0x40, 0xb7, 0x5f,
	0xc2, 0x91, 0x4b, 0x32, 0x72, 0x73, 0x8b, 0xdf, 0x3e, 0x0c, 0x97, 0xdf, 0x2f, 0xff, 0xb3, 0x7c,
	0xb5, 0xb2, 0x81, 0x54, 0xf9, 0x7d, 0x7c, 0xa7, 0x7c, 0x77, 0xf1, 0x71, 0xb1, 0x91, 0xdf, 0x06,
	0xfa, 0xf4, 0xbb, 0x0e, 0x26, 0x27, 0xb8, 0x20, 0xe5, 0x75, 0x1a, 0x13, 0x74, 0x0a, 0xd0, 0x79,
	0x13, 0x1d, 0x4b, 0x1d, 0x8a, 0xc5, 0x1f, 0x5a, 0x6a, 0xa2, 0x59, 0x65, 0x0e, 0xfb, 0xad, 0x63,
	0xd0, 0xfd, 0x6d, 0x07, 0xc9, 0xe6, 0x07, 0xbb, 0x8d, 0xc5, 0xb9, 0xbb, 0x07, 0x6b, 0xb9, 0x15,
	0x8b, 0xb4, 0xdc, 0x3b, 0x5c, 0x70, 0x0a, 0xd0, 0x9d, 0xac, 0x1d, 0xa0, 0xbc, 0x4e, 0x3b, 0x40,
	0xbd, 0xee, 0xd9, 0xc9, 0x17, 0x27, 0x49, 0xd9, 0x55, 0x1d, 0x4d, 0x62, 0xba, 0x76, 0x70, 0xfe,
	0xad, 0x3a, 0x71, 0x92, 0xb2, 0x88, 0x5f, 0xad, 0x69, 0x9e, 0x50, 0xa7, 0x22, 0xe5, 0x35, 0x29,
	0x9d, 0x35, 0xc5, 0x24, 0x73, 0xf8, 0x8c, 0x22, 0x8a, 0x86, 0xe2, 0x9f, 0x33, 0xfb, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x87, 0x85, 0x33, 0xe1, 0x81, 0x04, 0x00, 0x00,
}
