// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog.proto

// Service for creating, reading, updating, and deleting Blog items.

package blogpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The status of reading the blog from the database.
type ReadBlogResponse_ReadStatus int32

const (
	ReadBlogResponse_UNKNOWN   ReadBlogResponse_ReadStatus = 0
	ReadBlogResponse_NOT_FOUND ReadBlogResponse_ReadStatus = 1
	ReadBlogResponse_FOUND     ReadBlogResponse_ReadStatus = 2
)

var ReadBlogResponse_ReadStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_FOUND",
	2: "FOUND",
}

var ReadBlogResponse_ReadStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"NOT_FOUND": 1,
	"FOUND":     2,
}

func (x ReadBlogResponse_ReadStatus) String() string {
	return proto.EnumName(ReadBlogResponse_ReadStatus_name, int32(x))
}

func (ReadBlogResponse_ReadStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{4, 0}
}

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// A request with the blog to create in the database
type CreateBlogRequest struct {
	// The blog item to create in the database
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRequest) Reset()         { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()    {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}

func (m *CreateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequest.Unmarshal(m, b)
}
func (m *CreateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequest.Marshal(b, m, deterministic)
}
func (m *CreateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequest.Merge(m, src)
}
func (m *CreateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequest.Size(m)
}
func (m *CreateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequest proto.InternalMessageInfo

func (m *CreateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

// A response with the newly-created blog
type CreateBlogResponse struct {
	// The newly created blog with a set ID field
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogResponse) Reset()         { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()    {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}

func (m *CreateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogResponse.Unmarshal(m, b)
}
func (m *CreateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogResponse.Marshal(b, m, deterministic)
}
func (m *CreateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogResponse.Merge(m, src)
}
func (m *CreateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBlogResponse.Size(m)
}
func (m *CreateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogResponse proto.InternalMessageInfo

func (m *CreateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

// A request with the blog id to read from the database
type ReadBlogRequest struct {
	// The blog's database identifier
	BlogId               string   `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogRequest) Reset()         { *m = ReadBlogRequest{} }
func (m *ReadBlogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBlogRequest) ProtoMessage()    {}
func (*ReadBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{3}
}

func (m *ReadBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogRequest.Unmarshal(m, b)
}
func (m *ReadBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogRequest.Marshal(b, m, deterministic)
}
func (m *ReadBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogRequest.Merge(m, src)
}
func (m *ReadBlogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBlogRequest.Size(m)
}
func (m *ReadBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogRequest proto.InternalMessageInfo

func (m *ReadBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

// A response with the blog item and a status code.
type ReadBlogResponse struct {
	// The blog, if successfully found in the database.
	// This will be null if not found.
	Blog *Blog `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	// The status of reading the blog from the database.
	// This will be NOT_FOUND when the blog couldn't be
	// retrieved or FOUND when it could. Defaults to UNKNOWN
	// in cases of internal errors or unimplemented code.
	Status               ReadBlogResponse_ReadStatus `protobuf:"varint,2,opt,name=status,proto3,enum=blog.ReadBlogResponse_ReadStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ReadBlogResponse) Reset()         { *m = ReadBlogResponse{} }
func (m *ReadBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlogResponse) ProtoMessage()    {}
func (*ReadBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{4}
}

func (m *ReadBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogResponse.Unmarshal(m, b)
}
func (m *ReadBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogResponse.Marshal(b, m, deterministic)
}
func (m *ReadBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogResponse.Merge(m, src)
}
func (m *ReadBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlogResponse.Size(m)
}
func (m *ReadBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogResponse proto.InternalMessageInfo

func (m *ReadBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func (m *ReadBlogResponse) GetStatus() ReadBlogResponse_ReadStatus {
	if m != nil {
		return m.Status
	}
	return ReadBlogResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("blog.ReadBlogResponse_ReadStatus", ReadBlogResponse_ReadStatus_name, ReadBlogResponse_ReadStatus_value)
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogRequest)(nil), "blog.CreateBlogRequest")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
	proto.RegisterType((*ReadBlogRequest)(nil), "blog.ReadBlogRequest")
	proto.RegisterType((*ReadBlogResponse)(nil), "blog.ReadBlogResponse")
}

func init() {
	proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1)
}

var fileDescriptor_6745b25902462fb1 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xb1, 0x5f, 0x99, 0x62, 0xad, 0x83, 0xda, 0xa0, 0x20, 0x9a, 0x93, 0x08, 0x36, 0xb4,
	0xf5, 0xd2, 0x93, 0x50, 0x45, 0x28, 0x42, 0x0a, 0xa9, 0x45, 0xf0, 0x52, 0x92, 0xec, 0x92, 0x06,
	0xd2, 0x6c, 0xcc, 0x6e, 0x0a, 0xfe, 0x04, 0xff, 0x86, 0xbf, 0x54, 0xb2, 0xdb, 0xda, 0xd2, 0x0a,
	0x7a, 0xdb, 0x79, 0xf3, 0xde, 0xbc, 0x37, 0xc3, 0x02, 0xf8, 0x31, 0x0b, 0xdb, 0x69, 0xc6, 0x04,
	0xc3, 0x52, 0xf1, 0xb6, 0x02, 0x28, 0x0d, 0x62, 0x16, 0x62, 0x03, 0xf4, 0x88, 0x98, 0xda, 0xa5,
	0x76, 0x6d, 0xb8, 0x7a, 0x44, 0xf0, 0x1c, 0x0c, 0x2f, 0x17, 0x33, 0x96, 0x4d, 0x23, 0x62, 0xea,
	0x12, 0xae, 0x29, 0x60, 0x48, 0xf0, 0x18, 0xca, 0x22, 0x12, 0x31, 0x35, 0xf7, 0x65, 0x43, 0x15,
	0x68, 0x42, 0x35, 0x60, 0x89, 0xa0, 0x89, 0x30, 0x4b, 0x12, 0x5f, 0x95, 0x56, 0x0f, 0x8e, 0x1e,
	0x32, 0xea, 0x09, 0x5a, 0x58, 0xb9, 0xf4, 0x3d, 0xa7, 0x5c, 0xe0, 0x05, 0xc8, 0x04, 0xd2, 0xb3,
	0xde, 0x85, 0xb6, 0x8c, 0x26, 0x09, 0x2a, 0xd9, 0x1d, 0xe0, 0xa6, 0x88, 0xa7, 0x2c, 0xe1, 0xf4,
	0x4f, 0xd5, 0x0d, 0x1c, 0xba, 0xd4, 0x23, 0x9b, 0x46, 0x2d, 0xa8, 0x16, 0xad, 0xe9, 0xcf, 0x7e,
	0x95, 0xa2, 0x1c, 0x12, 0xeb, 0x4b, 0x83, 0xe6, 0x9a, 0xfc, 0x3f, 0x03, 0xec, 0x43, 0x85, 0x0b,
	0x4f, 0xe4, 0x5c, 0x5e, 0xa5, 0xd1, 0xbd, 0x52, 0x8c, 0xed, 0x39, 0x12, 0x18, 0x4b, 0xa2, 0xbb,
	0x14, 0x58, 0x3d, 0x80, 0x35, 0x8a, 0x75, 0xa8, 0x4e, 0x9c, 0x67, 0x67, 0xf4, 0xea, 0x34, 0xf7,
	0xf0, 0x00, 0x0c, 0x67, 0xf4, 0x32, 0x7d, 0x1a, 0x4d, 0x9c, 0xc7, 0xa6, 0x86, 0x06, 0x94, 0xd5,
	0x53, 0xef, 0x7e, 0x6a, 0x50, 0x2f, 0x06, 0x8f, 0x69, 0xb6, 0x88, 0x02, 0x8a, 0xf7, 0x00, 0xeb,
	0xb3, 0x60, 0x4b, 0xb9, 0xef, 0x5c, 0xf7, 0xcc, 0xdc, 0x6d, 0x2c, 0x17, 0xec, 0x43, 0x6d, 0x15,
	0x16, 0x4f, 0xb6, 0xc3, 0x2b, 0xf1, 0xe9, 0xef, 0x3b, 0x0d, 0x3a, 0x6f, 0x76, 0x18, 0x89, 0x59,
	0xee, 0xb7, 0x03, 0x36, 0xb7, 0x49, 0xf2, 0xc1, 0x3b, 0x76, 0x98, 0xa5, 0xc1, 0xed, 0x9c, 0x25,
	0x21, 0xb3, 0x39, 0xcd, 0x16, 0x34, 0xb3, 0xe7, 0x8c, 0xd0, 0xd8, 0x2e, 0x26, 0xa4, 0xbe, 0x5f,
	0x91, 0x9f, 0xad, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x0d, 0xed, 0x74, 0x7a, 0x02, 0x00,
	0x00,
}
